name = "RepeatingDecimalNotations"
uuid = "fbb887af-2519-40af-8dc5-25186fd85022"
authors = ["hyrodium <hyrodium@gmail.com>"]
version = "0.1.3"

[compat]
Aqua = "0.8"
Test = "1"
julia = "1.6"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
